# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(310, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 291, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tcp_type_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tcp_type_edit.setObjectName("tcp_type_edit")
        self.gridLayout.addWidget(self.tcp_type_edit, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.tcp_connected_btn = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.tcp_connected_btn.setObjectName("tcp_connected_btn")
        self.gridLayout.addWidget(self.tcp_connected_btn, 0, 3, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 291, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.tcp_ip_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.tcp_ip_edit.setObjectName("tcp_ip_edit")
        self.gridLayout_2.addWidget(self.tcp_ip_edit, 0, 1, 1, 1)
        self.tcp_port_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.tcp_port_edit.setObjectName("tcp_port_edit")
        self.gridLayout_2.addWidget(self.tcp_port_edit, 1, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 130, 291, 41))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 170, 291, 81))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sensor_box3 = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.sensor_box3.setObjectName("sensor_box3")
        self.gridLayout_4.addWidget(self.sensor_box3, 0, 3, 1, 1)
        self.sensor_box2 = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.sensor_box2.setObjectName("sensor_box2")
        self.gridLayout_4.addWidget(self.sensor_box2, 0, 2, 1, 1)
        self.sensor_count = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.sensor_count.setObjectName("sensor_count")
        self.gridLayout_4.addWidget(self.sensor_count, 0, 0, 1, 1)
        self.sensor_box1 = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.sensor_box1.setObjectName("sensor_box1")
        self.gridLayout_4.addWidget(self.sensor_box1, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.sensor_state_edit1 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.sensor_state_edit1.setObjectName("sensor_state_edit1")
        self.gridLayout_4.addWidget(self.sensor_state_edit1, 1, 1, 1, 1)
        self.sensor_state_edit2 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.sensor_state_edit2.setObjectName("sensor_state_edit2")
        self.gridLayout_4.addWidget(self.sensor_state_edit2, 1, 2, 1, 1)
        self.sensor_state_edit3 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.sensor_state_edit3.setObjectName("sensor_state_edit3")
        self.gridLayout_4.addWidget(self.sensor_state_edit3, 1, 3, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 250, 291, 444))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tcp_event_log = QtWidgets.QTextBrowser(self.gridLayoutWidget_5)
        self.tcp_event_log.setObjectName("tcp_event_log")
        self.gridLayout_5.addWidget(self.tcp_event_log, 3, 0, 1, 1)
        self.tcp_error_log = QtWidgets.QTextBrowser(self.gridLayoutWidget_5)
        self.tcp_error_log.setObjectName("tcp_error_log")
        self.gridLayout_5.addWidget(self.tcp_error_log, 5, 0, 1, 1)
        self.sensors_data_log = QtWidgets.QTextBrowser(self.gridLayoutWidget_5)
        self.sensors_data_log.setObjectName("sensors_data_log")
        self.gridLayout_5.addWidget(self.sensors_data_log, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TCP_TYPE "))
        self.tcp_connected_btn.setText(_translate("MainWindow", "TCP_CONNECTED"))
        self.label_2.setText(_translate("MainWindow", "TCP_IP"))
        self.label_3.setText(_translate("MainWindow", "TCP_PORT"))
        self.label_4.setText(_translate("MainWindow", "SENSOR"))
        self.sensor_count.setText(_translate("MainWindow", "COUNT"))
        self.label_6.setText(_translate("MainWindow", "STATE"))
        self.label_9.setText(_translate("MainWindow", "TCP ERROR"))
        self.label_5.setText(_translate("MainWindow", "SENSORS DATA"))
        self.label_8.setText(_translate("MainWindow", "TCP EVENT"))
