# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setGeometry(QtCore.QRect(20, 120, 113, 32))
        self.btn_back.setObjectName("btn_back")
        self.btn_welcome = QtWidgets.QPushButton(self.centralwidget)
        self.btn_welcome.setGeometry(QtCore.QRect(20, 170, 113, 32))
        self.btn_welcome.setObjectName("btn_welcome")
        self.btn_add_text = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_text.setGeometry(QtCore.QRect(20, 220, 113, 32))
        self.btn_add_text.setObjectName("btn_add_text")
        self.btn_del_text = QtWidgets.QPushButton(self.centralwidget)
        self.btn_del_text.setGeometry(QtCore.QRect(20, 270, 113, 32))
        self.btn_del_text.setStyleSheet("QPushButton \n"
"    {\n"
"        background-color: rgba(255, 30, 30, 1);\n"
"        border-radius: 10px;\n"
"        border: none;\n"
"    }\n"
"    QPushButton:hover:!pressed \n"
"    { \n"
"        background-color: rgba(20, 255, 20, 1);\n"
"    }\n"
"    QPushButton:hover:pressed \n"
"    { \n"
"        background-color: rgba(10, 10, 255, 1); \n"
"    }")
        self.btn_del_text.setObjectName("btn_del_text")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(20, 0, 120, 111))
        self.widget_2.setObjectName("widget_2")
        self.btn_forward = QtWidgets.QPushButton(self.widget_2)
        self.btn_forward.setGeometry(QtCore.QRect(0, 40, 113, 32))
        self.btn_forward.setStyleSheet("QPushButton \n"
"    {\n"
"        background-color: rgba(255, 30, 30, 1);\n"
"        border-radius: 10px;\n"
"        border: none;\n"
"    }\n"
"    QPushButton:hover:!pressed \n"
"    { \n"
"        background-color: rgba(20, 255, 20, 1);\n"
"    }\n"
"    QPushButton:hover:pressed \n"
"    { \n"
"        background-color: rgba(10, 10, 255, 1); \n"
"    }")
        self.btn_forward.setObjectName("btn_forward")
        self.btn_stop = QtWidgets.QPushButton(self.widget_2)
        self.btn_stop.setGeometry(QtCore.QRect(0, 80, 113, 32))
        self.btn_stop.setStyleSheet("QPushButton \n"
"    {\n"
"        background-color: rgba(255, 30, 30, 1);\n"
"        border-radius: 10px;\n"
"        border: none;\n"
"    }\n"
"    QPushButton:hover:!pressed \n"
"    { \n"
"        background-color: rgba(20, 255, 20, 1);\n"
"    }\n"
"    QPushButton:hover:pressed \n"
"    { \n"
"        background-color: rgba(10, 10, 255, 1); \n"
"    }")
        self.btn_stop.setObjectName("btn_stop")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_back.setText(_translate("MainWindow", "back"))
        self.btn_welcome.setText(_translate("MainWindow", "welcome"))
        self.btn_add_text.setText(_translate("MainWindow", "addtext"))
        self.btn_del_text.setText(_translate("MainWindow", "deltext"))
        self.btn_forward.setText(_translate("MainWindow", "forward"))
        self.btn_stop.setText(_translate("MainWindow", "stop"))
