buttons = {0: 'A',
           1: 'B',
           2: 'X',
           3: 'Y',
           4: 'Return',
           5: 'Charging',
           6: 'Stop',
           7: '',
           8: '',
           9: 'LB',
           10: 'RB',
           11: 'Up',
           12: 'Down',
           13: 'Left',
           14: 'Right'}
axies = {'LT': [4],
         'RT': [5],
         'R-r-u pressed': [3, -2],
         'R-r-d pressed': [3, 2],
         'R-r-l pressed': [2, 2],
         'R-r-r pressed': [2, -2],
         'R-r-u released': [3, 1],
         'R-r-d released': [3, -1],
         'R-r-l released': [2, -1],
         'R-r-r released': [2, 1]}