# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(270, 662)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 251, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ip_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.ip_edit.setObjectName("ip_edit")
        self.gridLayout.addWidget(self.ip_edit, 0, 1, 1, 1)
        self.port_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.port_edit.setObjectName("port_edit")
        self.gridLayout.addWidget(self.port_edit, 1, 1, 1, 1)
        self.tcp_connect_btn = QtWidgets.QCheckBox(self.centralwidget)
        self.tcp_connect_btn.setGeometry(QtCore.QRect(140, 10, 120, 20))
        self.tcp_connect_btn.setObjectName("tcp_connect_btn")
        self.sensor_data_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.sensor_data_log.setGeometry(QtCore.QRect(10, 220, 250, 115))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.sensor_data_log.setFont(font)
        self.sensor_data_log.setObjectName("sensor_data_log")
        self.error_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.error_log.setGeometry(QtCore.QRect(10, 360, 250, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.error_log.setFont(font)
        self.error_log.setObjectName("error_log")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 120, 251, 32))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.sensor_btn_start = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.sensor_btn_start.setObjectName("sensor_btn_start")
        self.gridLayout_2.addWidget(self.sensor_btn_start, 0, 1, 1, 1)
        self.sensor_stop_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.sensor_stop_btn.setObjectName("sensor_stop_btn")
        self.gridLayout_2.addWidget(self.sensor_stop_btn, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 340, 60, 20))
        self.label_4.setObjectName("label_4")
        self.event_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.event_log.setGeometry(QtCore.QRect(10, 460, 250, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.event_log.setFont(font)
        self.event_log.setObjectName("event_log")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 440, 71, 20))
        self.label_5.setObjectName("label_5")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 160, 258, 30))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sensor_box2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.sensor_box2.setObjectName("sensor_box2")
        self.gridLayout_3.addWidget(self.sensor_box2, 0, 2, 1, 1)
        self.sensor_box1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.sensor_box1.setObjectName("sensor_box1")
        self.gridLayout_3.addWidget(self.sensor_box1, 0, 1, 1, 1)
        self.sensor_box3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.sensor_box3.setObjectName("sensor_box3")
        self.gridLayout_3.addWidget(self.sensor_box3, 0, 3, 1, 1)
        self.sensor_stand = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.sensor_stand.setFont(font)
        self.sensor_stand.setObjectName("sensor_stand")
        self.gridLayout_3.addWidget(self.sensor_stand, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 200, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 550, 60, 16))
        self.label_6.setObjectName("label_6")
        self.recv_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.recv_log.setGeometry(QtCore.QRect(9, 570, 251, 80))
        self.recv_log.setObjectName("recv_log")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "PORT"))
        self.label.setText(_translate("MainWindow", "MY_IP"))
        self.tcp_connect_btn.setText(_translate("MainWindow", "tcp_connected"))
        self.label_3.setText(_translate("MainWindow", "Sensor"))
        self.sensor_btn_start.setText(_translate("MainWindow", "start"))
        self.sensor_stop_btn.setText(_translate("MainWindow", "stop"))
        self.label_4.setText(_translate("MainWindow", "TCP error"))
        self.label_5.setText(_translate("MainWindow", "TCP event"))
        self.sensor_stand.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Sensor data"))
        self.label_6.setText(_translate("MainWindow", "TCP recv"))
