# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(271, 137)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(50, 20, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal{"
                                            "height: 10px;"  # 高
                                            "background: #C0C0C0;"  # 颜色
                                            "border: 1px solid #4A708B;"  # 边框 + 颜色
                                            "border-radius: 5px;}\n"  # 边角圆滑度
                                            # "padding-left:1px;"  # 
                                            # "padding-right:1px;}\n"  # 
                                            "QSlider::handle:horizontal"  # 滑块
                                            "{background-color: black; "  # 滑块颜色
                                            "border: 1px; "  # 边框
                                            "width: 20px; "  # 宽
                                            "margin: -5px 0;"  # 边距， 距离槽的上下边距， 第二个是左右边距
                                            "border-radius: 10px"  # 滑块圆角
                                            "}\n"
                                            "QSlider::add-page:qlineargradient {"  # 滑块右侧未加载样式设置
                                            "background: white;"  # 颜色
                                            "border-top-right-radius: 5px;"  # 右上角圆度
                                            "border-bottom-right-radius: 5px;"  # 右下角圆度
                                            "border-top-left-radius: 5px;"  # 左上角圆度
                                            "border-bottom-left-radius: 5px;}\n"  # 左下角圆度
                                            "QSlider::sub-page:qlineargradient {"  # 滑块左侧已经加载样式设置
                                            "background: red;"  # 背景颜色
                                            "border-top-right-radius: 5px;"
                                            "border-bottom-right-radius: 5px;"
                                            "border-top-left-radius: 5px;"
                                            "border-bottom-left-radius: 5px;}")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 60, 113, 51))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        # self.pushButton.setStyleSheet("QPushButton:hover:!pressed { "  # 按钮选中但是没按下设置
        #                               "background-color: rgb(127, 220, 245);"  # 背景颜色
        #                               "border-style: inset;"  # 边框风格  outset inset
        #                               "border-width: 1px; "  # 边框线宽
        #                               "border-color: rgb(0, 255, 0); "  # 边框颜色
        #                               "border-radius: 5px;"  # 边角圆度
        #                               "color: rgb(0, 255, 0)}"  # 按钮上字体颜色
        #                               "QPushButton:hover:pressed { "  # 按钮按下设置
        #                               "background-color: rgb(127, 220, 245);"  # 背景颜色
        #                               "border-style: inset;"
        #                               "border-width: 1px; "
        #                               "border-color: red; "
        #                               "border-radius: 5px;"
        #                               "color: rgb(0, 255, 0)}"
        #                               "QPushButton {"
        #                               "background-color: rgb(127, 220, 245);"
        #                               "border-style: outset;"
        #                               "border-width: 1px; "
        #                               "border-color: beige;"
        #                               "color: rgb(0, 255, 0)}")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
