# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(280, 780)
        MainWindow.setMinimumSize(QtCore.QSize(280, 780))
        MainWindow.setMaximumSize(QtCore.QSize(280, 800))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ui_tcp_bind = QtWidgets.QRadioButton(self.centralwidget)
        self.ui_tcp_bind.setGeometry(QtCore.QRect(160, 20, 90, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ui_tcp_bind.setFont(font)
        self.ui_tcp_bind.setAutoExclusive(False)
        self.ui_tcp_bind.setObjectName("ui_tcp_bind")
        self.ui_tcp_connected = QtWidgets.QRadioButton(self.centralwidget)
        self.ui_tcp_connected.setGeometry(QtCore.QRect(160, 0, 120, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ui_tcp_connected.setFont(font)
        self.ui_tcp_connected.setAutoExclusive(False)
        self.ui_tcp_connected.setObjectName("ui_tcp_connected")
        self.ui_inviter_ena = QtWidgets.QCheckBox(self.centralwidget)
        self.ui_inviter_ena.setGeometry(QtCore.QRect(0, 0, 120, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ui_inviter_ena.setFont(font)
        self.ui_inviter_ena.setChecked(True)
        self.ui_inviter_ena.setObjectName("ui_inviter_ena")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 40, 280, 150))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 50, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ui_server_ip = QtWidgets.QLineEdit(self.groupBox)
        self.ui_server_ip.setGeometry(QtCore.QRect(70, 50, 140, 21))
        self.ui_server_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_server_ip.setObjectName("ui_server_ip")
        self.ui_server_port = QtWidgets.QLineEdit(self.groupBox)
        self.ui_server_port.setGeometry(QtCore.QRect(210, 50, 60, 21))
        self.ui_server_port.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_server_port.setObjectName("ui_server_port")
        self.ui_clients = QtWidgets.QTableWidget(self.groupBox)
        self.ui_clients.setGeometry(QtCore.QRect(10, 70, 260, 80))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ui_clients.setFont(font)
        self.ui_clients.setObjectName("ui_clients")
        self.ui_clients.setColumnCount(2)
        self.ui_clients.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.ui_clients.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_clients.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ui_clients.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.ui_clients.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.ui_clients.setHorizontalHeaderItem(1, item)
        self.ui_clients.verticalHeader().setDefaultSectionSize(20)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.ui_device_token = QtWidgets.QLineEdit(self.groupBox)
        self.ui_device_token.setGeometry(QtCore.QRect(70, 20, 81, 21))
        self.ui_device_token.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_device_token.setObjectName("ui_device_token")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(160, 20, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.ui_device_type = QtWidgets.QLineEdit(self.groupBox)
        self.ui_device_type.setGeometry(QtCore.QRect(210, 20, 61, 21))
        self.ui_device_type.setAlignment(QtCore.Qt.AlignCenter)
        self.ui_device_type.setObjectName("ui_device_type")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 190, 280, 70))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.ui_tx_msg = QtWidgets.QLineEdit(self.groupBox_2)
        self.ui_tx_msg.setGeometry(QtCore.QRect(10, 20, 90, 21))
        self.ui_tx_msg.setObjectName("ui_tx_msg")
        self.ui_broadcast = QtWidgets.QCheckBox(self.groupBox_2)
        self.ui_broadcast.setGeometry(QtCore.QRect(110, 20, 90, 18))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ui_broadcast.setFont(font)
        self.ui_broadcast.setChecked(True)
        self.ui_broadcast.setObjectName("ui_broadcast")
        self.btn_tcp_send = QtWidgets.QToolButton(self.groupBox_2)
        self.btn_tcp_send.setGeometry(QtCore.QRect(200, 20, 69, 22))
        self.btn_tcp_send.setObjectName("btn_tcp_send")
        self.btn_bad_1 = QtWidgets.QToolButton(self.groupBox_2)
        self.btn_bad_1.setGeometry(QtCore.QRect(10, 40, 40, 22))
        self.btn_bad_1.setObjectName("btn_bad_1")
        self.btn_bad_2 = QtWidgets.QToolButton(self.groupBox_2)
        self.btn_bad_2.setGeometry(QtCore.QRect(50, 40, 40, 22))
        self.btn_bad_2.setObjectName("btn_bad_2")
        self.btn_bad_3 = QtWidgets.QToolButton(self.groupBox_2)
        self.btn_bad_3.setGeometry(QtCore.QRect(90, 40, 40, 22))
        self.btn_bad_3.setObjectName("btn_bad_3")
        self.btn_bad_4 = QtWidgets.QToolButton(self.groupBox_2)
        self.btn_bad_4.setGeometry(QtCore.QRect(130, 40, 40, 22))
        self.btn_bad_4.setObjectName("btn_bad_4")
        self.btn_bad_5 = QtWidgets.QToolButton(self.groupBox_2)
        self.btn_bad_5.setGeometry(QtCore.QRect(170, 40, 40, 22))
        self.btn_bad_5.setObjectName("btn_bad_5")
        self.btn_send_loop = QtWidgets.QToolButton(self.groupBox_2)
        self.btn_send_loop.setGeometry(QtCore.QRect(230, 40, 40, 22))
        self.btn_send_loop.setObjectName("btn_send_loop")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 260, 280, 110))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.ui_log_event = QtWidgets.QTextBrowser(self.groupBox_3)
        self.ui_log_event.setGeometry(QtCore.QRect(0, 20, 280, 90))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ui_log_event.setFont(font)
        self.ui_log_event.setObjectName("ui_log_event")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 480, 280, 140))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.ui_log_recv = QtWidgets.QTextBrowser(self.groupBox_4)
        self.ui_log_recv.setGeometry(QtCore.QRect(0, 20, 280, 120))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ui_log_recv.setFont(font)
        self.ui_log_recv.setObjectName("ui_log_recv")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 370, 280, 110))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.ui_log_inviter = QtWidgets.QTextBrowser(self.groupBox_5)
        self.ui_log_inviter.setGeometry(QtCore.QRect(0, 20, 280, 90))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ui_log_inviter.setFont(font)
        self.ui_log_inviter.setObjectName("ui_log_inviter")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 630, 280, 140))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.ui_log_error = QtWidgets.QTextBrowser(self.groupBox_6)
        self.ui_log_error.setGeometry(QtCore.QRect(0, 20, 280, 120))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ui_log_error.setFont(font)
        self.ui_log_error.setObjectName("ui_log_error")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutoNET_SERVER"))
        self.ui_tcp_bind.setText(_translate("MainWindow", "TCP_BIND"))
        self.ui_tcp_connected.setText(_translate("MainWindow", "TCP_CONNECTED"))
        self.ui_inviter_ena.setText(_translate("MainWindow", "INVITER ENA"))
        self.groupBox.setTitle(_translate("MainWindow", "DEVICE"))
        self.label.setText(_translate("MainWindow", "SERVER_IP"))
        item = self.ui_clients.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.ui_clients.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.ui_clients.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.ui_clients.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IP"))
        item = self.ui_clients.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Status"))
        self.label_4.setText(_translate("MainWindow", "TOKEN"))
        self.label_6.setText(_translate("MainWindow", "TYPE"))
        self.groupBox_2.setTitle(_translate("MainWindow", "TX"))
        self.ui_tx_msg.setText(_translate("MainWindow", "Hello"))
        self.ui_broadcast.setText(_translate("MainWindow", "BROADCAST"))
        self.btn_tcp_send.setText(_translate("MainWindow", "TCP_SEND"))
        self.btn_bad_1.setText(_translate("MainWindow", "BAD_1"))
        self.btn_bad_2.setText(_translate("MainWindow", "BAD_2"))
        self.btn_bad_3.setText(_translate("MainWindow", "BAD_3"))
        self.btn_bad_4.setText(_translate("MainWindow", "BAD_4"))
        self.btn_bad_5.setText(_translate("MainWindow", "BAD_5"))
        self.btn_send_loop.setText(_translate("MainWindow", "LOOP"))
        self.groupBox_3.setTitle(_translate("MainWindow", "ANET_EVENT"))
        self.groupBox_4.setTitle(_translate("MainWindow", "RX"))
        self.groupBox_5.setTitle(_translate("MainWindow", "INVITER"))
        self.groupBox_6.setTitle(_translate("MainWindow", "ERROR"))
