# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(184, 65)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_water_inflow = QtWidgets.QCheckBox(self.centralwidget)
        self.btn_water_inflow.setGeometry(QtCore.QRect(20, 20, 87, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_water_inflow.setFont(font)
        self.btn_water_inflow.setObjectName("btn_water_inflow")
        self.led_water_inflow = QtWidgets.QPushButton(self.centralwidget)
        self.led_water_inflow.setGeometry(QtCore.QRect(120, 11, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.led_water_inflow.setFont(font)
        self.led_water_inflow.setText("")
        self.led_water_inflow.setObjectName("led_water_inflow")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_water_inflow.setText(_translate("MainWindow", "WATERINFLOW"))
