# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(310, 665)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 291, 31))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.tcp_type_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.tcp_type_edit.setFont(font)
        self.tcp_type_edit.setObjectName("tcp_type_edit")
        self.gridLayout.addWidget(self.tcp_type_edit, 0, 2, 1, 1)
        self.tcp_connected_btn = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tcp_connected_btn.setFont(font)
        self.tcp_connected_btn.setObjectName("tcp_connected_btn")
        self.gridLayout.addWidget(self.tcp_connected_btn, 0, 3, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 291, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.tcp_ip_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.tcp_ip_edit.setFont(font)
        self.tcp_ip_edit.setObjectName("tcp_ip_edit")
        self.gridLayout_2.addWidget(self.tcp_ip_edit, 0, 1, 1, 1)
        self.tcp_port_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.tcp_port_edit.setFont(font)
        self.tcp_port_edit.setObjectName("tcp_port_edit")
        self.gridLayout_2.addWidget(self.tcp_port_edit, 1, 1, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 140, 291, 31))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.sensor_box2 = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.sensor_box2.setFont(font)
        self.sensor_box2.setObjectName("sensor_box2")
        self.gridLayout_4.addWidget(self.sensor_box2, 0, 2, 1, 1)
        self.sensor_box3 = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.sensor_box3.setFont(font)
        self.sensor_box3.setObjectName("sensor_box3")
        self.gridLayout_4.addWidget(self.sensor_box3, 0, 3, 1, 1)
        self.sensor_count = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.sensor_count.setFont(font)
        self.sensor_count.setObjectName("sensor_count")
        self.gridLayout_4.addWidget(self.sensor_count, 0, 0, 1, 1)
        self.sensor_box1 = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.sensor_box1.setFont(font)
        self.sensor_box1.setObjectName("sensor_box1")
        self.gridLayout_4.addWidget(self.sensor_box1, 0, 1, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 180, 291, 471))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.event_log = QtWidgets.QTextBrowser(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.event_log.setFont(font)
        self.event_log.setObjectName("event_log")
        self.gridLayout_5.addWidget(self.event_log, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 4, 0, 1, 1)
        self.inviter_log = QtWidgets.QTextBrowser(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.inviter_log.setFont(font)
        self.inviter_log.setObjectName("inviter_log")
        self.gridLayout_5.addWidget(self.inviter_log, 3, 0, 1, 1)
        self.data_log = QtWidgets.QTextBrowser(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.data_log.setFont(font)
        self.data_log.setObjectName("data_log")
        self.gridLayout_5.addWidget(self.data_log, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.recv_log = QtWidgets.QTextBrowser(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.recv_log.setFont(font)
        self.recv_log.setObjectName("recv_log")
        self.gridLayout_5.addWidget(self.recv_log, 7, 0, 1, 1)
        self.inviter_works = QtWidgets.QCheckBox(self.centralwidget)
        self.inviter_works.setGeometry(QtCore.QRect(10, 10, 291, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.inviter_works.setFont(font)
        self.inviter_works.setChecked(True)
        self.inviter_works.setObjectName("inviter_works")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TCP_TYPE "))
        self.tcp_connected_btn.setText(_translate("MainWindow", "TCP_CONNECT"))
        self.label_2.setText(_translate("MainWindow", "TCP_IP"))
        self.label_3.setText(_translate("MainWindow", "TCP_PORT"))
        self.sensor_count.setText(_translate("MainWindow", "SENSOR STATE"))
        self.label_8.setText(_translate("MainWindow", "INVITER"))
        self.label_9.setText(_translate("MainWindow", "EVENT"))
        self.label_4.setText(_translate("MainWindow", "RECV"))
        self.label_5.setText(_translate("MainWindow", "SENSORS GuideWork"))
        self.inviter_works.setText(_translate("MainWindow", "INVITER_WORKS"))
